/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "测试",
  "description": "凌览，微信搜索「程序员凌览」关注我，长期交流学习。不知名前端，Node.js爱好者",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2f041896",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/avatar.png",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "博客",
        "link": "https://linglan01.cn/"
      },
      {
        "text": "掘金",
        "link": "https://juejin.cn/user/3350967174565198"
      },
      {
        "text": "Github",
        "link": "https://github.com/CatsAndMice"
      }
    ],
    "sidebar": [
      {
        "title": "Group 1",
        "path": "/introduce/",
        "collapsable": true,
        "sidebarDepth": 3,
        "children": [
          "/introduce/haha",
          "/"
        ]
      }
    ],
    "theme": "reco",
    "locales": {
      "/": {
        "lang": "zh-CN"
      }
    }
  }
}